spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ese10
    username: root
    password: 9876
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: SpringRepo1